[gcp_service_account]

cohere_api_key = "mLce2Wncyd6Cpv4WEsAVuJElVTnKQA3aGL776eAI"
PINECONE_API_KEY = "48cdec3d-76e5-4a8b-b931-6eeca75e076c"
TAVILY_API_KEY = "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"
OPENAI_API_KEY = "sk-proj-tymuOuG4sXN4tDpj9GXGT3BlbkFJa66Eox35dIijdwkrHP9B"
